plugins {
	id 'java'
	id 'groovy'
	id 'org.springframework.boot' version '2.5.14'
	id 'io.spring.dependency-management' version '1.1.7'
	id "io.freefair.lombok" version "6.5.0"
	id("org.springdoc.openapi-gradle-plugin") version "1.6.0"
}

group = 'com.bci'
version = '1.0-SNAPSHOT'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	runtimeOnly 'com.h2database:h2'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'

	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

	//Swagger
	implementation "org.springdoc:springdoc-openapi-ui:1.8.0"

	//Tests
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.spockframework:spock-core:2.3-groovy-4.0'
	testImplementation 'org.spockframework:spock-spring:2.3-groovy-4.0'
	testImplementation 'org.apache.groovy:groovy-json:4.0.9'

	//Jwt
	implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.12.6'
	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.12.6'
	runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.12.6'

	implementation 'com.fasterxml.jackson.core:jackson-databind:2.12.0'

	//MapStruct
	implementation 'org.mapstruct:mapstruct:1.5.3.Final'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'
	annotationProcessor "org.projectlombok:lombok-mapstruct-binding:0.2.0"

}

tasks.named('test') {
	useJUnitPlatform()
	systemProperty 'com.athaydes.spockframework.report.showCodeBlocks', true
	systemProperty 'com.athaydes.spockframework.report.outputDir', 'build/spock-reports/unit'
}

def exclusionList = [
		"**Application**",
		"**/dto**",
		"**/mappers**",
		"**/config**",
		"**/model**",
		"**/repository**",
		"**/resources**"
]

openApi {
	outputDir.set(file("$projectDir/docs"))
	outputFileName.set("swagger.json")
	waitTimeInSeconds.set(10)
}
